## NOTE: CI workflow overrides this baseURL via --baseURL using actions/configure-pages output
# Set to project path so local builds and GitHub Pages resolve correctly
baseURL = "https://himiyosh.github.io/HMStudio-T2/"
languageCode = "ja-jp"
title = "HMStudio"
theme = "careercanvas"

[params]
  name = "himiyosh"
  tagline = "T2 Blog"
  location = "Tokyo, Japan"
  email = "himiyosh.344@outlook.com"
  profile_image = "/images/profile.jpg"
  description = "A blog built with the CareerCanvas theme"
  author = "himiyosh"

  linkedin_url = "https://linkedin.com/in/himiyosh"
  github_url = "https://github.com/himiyosh"

[[params.social]]
  icon = "linkedin-in"
  url = "https://linkedin.com/in/himiyosh"

[[params.social]]
  icon = "github"
  url = "https://github.com/himiyosh"

[[menu.main]]
  name = "About"
  url = "/#about"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/#blog"
  weight = 2
